# Generated by Django 4.2.1 on 2023-05-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_component_created_at_component_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredienttype',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='salad',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
