# Generated by Django 4.2.1 on 2023-06-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customeraddress_options_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='users',
            new_name='user',
        ),
    ]
